//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import {
  mergeMap as _observableMergeMap,
  catchError as _observableCatch,
} from "rxjs/operators";
import {
  Observable,
  from as _observableFrom,
  throwError as _observableThrow,
  of as _observableOf,
} from "rxjs";
import { Injectable, Inject, Optional, InjectionToken } from "@angular/core";
import {
  HttpClient,
  HttpHeaders,
  HttpResponse,
  HttpResponseBase,
} from "@angular/common/http";
import { ApiBase } from "./api-base";

export const API_BASE_URL = new InjectionToken<string>("API_BASE_URL");

@Injectable()
export class AccountsClient extends ApiBase {
  private http: HttpClient;
  private baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(
    @Inject(HttpClient) http: HttpClient,
    @Optional() @Inject(API_BASE_URL) baseUrl?: string
  ) {
    super();
    this.http = http;
    this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
  }

  /**
   * @param body (optional)
   * @return Success
   */
  registerNewApplicant(
    body: RegistrationForm | undefined
  ): Observable<boolean> {
    let url_ = this.baseUrl + "/Accounts/RegisterNewApplicant";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: any = {
      body: content_,
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        "Content-Type": "application/json",
        Accept: "text/plain",
      }),
    };

    return _observableFrom(this.transformOptions(options_))
      .pipe(
        _observableMergeMap((transformedOptions_) => {
          return this.http.request("post", url_, transformedOptions_);
        })
      )
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processRegisterNewApplicant(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processRegisterNewApplicant(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<boolean>;
            }
          } else
            return _observableThrow(response_) as any as Observable<boolean>;
        })
      );
  }

  protected processRegisterNewApplicant(
    response: HttpResponseBase
  ): Observable<boolean> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          let result200: any = null;
          let resultData200 =
            _responseText === ""
              ? null
              : JSON.parse(_responseText, this.jsonParseReviver);
          result200 = resultData200 !== undefined ? resultData200 : <any>null;

          return _observableOf(result200);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          return throwException(
            "An unexpected server error occurred.",
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf(null as any);
  }

  /**
   * @param userName (optional)
   * @return Success
   */
  isUserNameTaken(userName: string | undefined): Observable<boolean> {
    let url_ = this.baseUrl + "/Accounts/IsUserNameTaken?";
    if (userName === null)
      throw new Error("The parameter 'userName' cannot be null.");
    else if (userName !== undefined)
      url_ += "userName=" + encodeURIComponent("" + userName) + "&";
    url_ = url_.replace(/[?&]$/, "");

    let options_: any = {
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        Accept: "text/plain",
      }),
    };

    return _observableFrom(this.transformOptions(options_))
      .pipe(
        _observableMergeMap((transformedOptions_) => {
          return this.http.request("get", url_, transformedOptions_);
        })
      )
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processIsUserNameTaken(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processIsUserNameTaken(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<boolean>;
            }
          } else
            return _observableThrow(response_) as any as Observable<boolean>;
        })
      );
  }

  protected processIsUserNameTaken(
    response: HttpResponseBase
  ): Observable<boolean> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          let result200: any = null;
          let resultData200 =
            _responseText === ""
              ? null
              : JSON.parse(_responseText, this.jsonParseReviver);
          result200 = resultData200 !== undefined ? resultData200 : <any>null;

          return _observableOf(result200);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          return throwException(
            "An unexpected server error occurred.",
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf(null as any);
  }

  /**
   * @param email (optional)
   * @return Success
   */
  isAlreadyRegistered(email: string | undefined): Observable<boolean> {
    let url_ = this.baseUrl + "/Accounts/IsAlreadyRegistered?";
    if (email === null)
      throw new Error("The parameter 'email' cannot be null.");
    else if (email !== undefined)
      url_ += "email=" + encodeURIComponent("" + email) + "&";
    url_ = url_.replace(/[?&]$/, "");

    let options_: any = {
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        Accept: "text/plain",
      }),
    };

    return _observableFrom(this.transformOptions(options_))
      .pipe(
        _observableMergeMap((transformedOptions_) => {
          return this.http.request("get", url_, transformedOptions_);
        })
      )
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processIsAlreadyRegistered(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processIsAlreadyRegistered(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<boolean>;
            }
          } else
            return _observableThrow(response_) as any as Observable<boolean>;
        })
      );
  }

  protected processIsAlreadyRegistered(
    response: HttpResponseBase
  ): Observable<boolean> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          let result200: any = null;
          let resultData200 =
            _responseText === ""
              ? null
              : JSON.parse(_responseText, this.jsonParseReviver);
          result200 = resultData200 !== undefined ? resultData200 : <any>null;

          return _observableOf(result200);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          return throwException(
            "An unexpected server error occurred.",
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf(null as any);
  }

  /**
   * @return Success
   */
  getAllApplicants(): Observable<ApplicantDTO[]> {
    let url_ = this.baseUrl + "/Accounts/GetAllApplicants";
    url_ = url_.replace(/[?&]$/, "");

    let options_: any = {
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        Accept: "text/plain",
      }),
    };

    return _observableFrom(this.transformOptions(options_))
      .pipe(
        _observableMergeMap((transformedOptions_) => {
          return this.http.request("get", url_, transformedOptions_);
        })
      )
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processGetAllApplicants(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processGetAllApplicants(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<ApplicantDTO[]>;
            }
          } else
            return _observableThrow(response_) as any as Observable<
              ApplicantDTO[]
            >;
        })
      );
  }

  protected processGetAllApplicants(
    response: HttpResponseBase
  ): Observable<ApplicantDTO[]> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          let result200: any = null;
          let resultData200 =
            _responseText === ""
              ? null
              : JSON.parse(_responseText, this.jsonParseReviver);
          if (Array.isArray(resultData200)) {
            result200 = [] as any;
            for (let item of resultData200)
              result200!.push(ApplicantDTO.fromJS(item));
          } else {
            result200 = <any>null;
          }
          return _observableOf(result200);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          return throwException(
            "An unexpected server error occurred.",
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf(null as any);
  }
}

@Injectable()
export class AuthClient extends ApiBase {
  private http: HttpClient;
  private baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(
    @Inject(HttpClient) http: HttpClient,
    @Optional() @Inject(API_BASE_URL) baseUrl?: string
  ) {
    super();
    this.http = http;
    this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
  }

  /**
   * @param body (optional)
   * @return Success
   */
  login(body: LoginRequest | undefined): Observable<AuthResponse> {
    let url_ = this.baseUrl + "/Auth/Login";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: any = {
      body: content_,
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        "Content-Type": "application/json",
        Accept: "text/plain",
      }),
    };

    return _observableFrom(this.transformOptions(options_))
      .pipe(
        _observableMergeMap((transformedOptions_) => {
          return this.http.request("post", url_, transformedOptions_);
        })
      )
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processLogin(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processLogin(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<AuthResponse>;
            }
          } else
            return _observableThrow(
              response_
            ) as any as Observable<AuthResponse>;
        })
      );
  }

  protected processLogin(response: HttpResponseBase): Observable<AuthResponse> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          let result200: any = null;
          let resultData200 =
            _responseText === ""
              ? null
              : JSON.parse(_responseText, this.jsonParseReviver);
          result200 = AuthResponse.fromJS(resultData200);
          return _observableOf(result200);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          return throwException(
            "An unexpected server error occurred.",
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf(null as any);
  }

  /**
   * @param refreshToken (optional)
   * @return Success
   */
  refreshAccessToken(
    refreshToken: string | undefined
  ): Observable<AuthResponse> {
    let url_ = this.baseUrl + "/Auth/RefreshAccessToken?";
    if (refreshToken === null)
      throw new Error("The parameter 'refreshToken' cannot be null.");
    else if (refreshToken !== undefined)
      url_ += "refreshToken=" + encodeURIComponent("" + refreshToken) + "&";
    url_ = url_.replace(/[?&]$/, "");

    let options_: any = {
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        Accept: "text/plain",
      }),
    };

    return _observableFrom(this.transformOptions(options_))
      .pipe(
        _observableMergeMap((transformedOptions_) => {
          return this.http.request("post", url_, transformedOptions_);
        })
      )
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processRefreshAccessToken(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processRefreshAccessToken(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<AuthResponse>;
            }
          } else
            return _observableThrow(
              response_
            ) as any as Observable<AuthResponse>;
        })
      );
  }

  protected processRefreshAccessToken(
    response: HttpResponseBase
  ): Observable<AuthResponse> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          let result200: any = null;
          let resultData200 =
            _responseText === ""
              ? null
              : JSON.parse(_responseText, this.jsonParseReviver);
          result200 = AuthResponse.fromJS(resultData200);
          return _observableOf(result200);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          return throwException(
            "An unexpected server error occurred.",
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf(null as any);
  }
}

export class ApplicantDTO implements IApplicantDTO {
  id?: number;
  fullName?: string | null;
  phoneNumber?: string | null;
  userName?: string | null;
  email?: string | null;

  constructor(data?: IApplicantDTO) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"] !== undefined ? _data["id"] : <any>null;
      this.fullName =
        _data["fullName"] !== undefined ? _data["fullName"] : <any>null;
      this.phoneNumber =
        _data["phoneNumber"] !== undefined ? _data["phoneNumber"] : <any>null;
      this.userName =
        _data["userName"] !== undefined ? _data["userName"] : <any>null;
      this.email = _data["email"] !== undefined ? _data["email"] : <any>null;
    }
  }

  static fromJS(data: any): ApplicantDTO {
    data = typeof data === "object" ? data : {};
    let result = new ApplicantDTO();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id !== undefined ? this.id : <any>null;
    data["fullName"] = this.fullName !== undefined ? this.fullName : <any>null;
    data["phoneNumber"] =
      this.phoneNumber !== undefined ? this.phoneNumber : <any>null;
    data["userName"] = this.userName !== undefined ? this.userName : <any>null;
    data["email"] = this.email !== undefined ? this.email : <any>null;
    return data;
  }
}

export interface IApplicantDTO {
  id?: number;
  fullName?: string | null;
  phoneNumber?: string | null;
  userName?: string | null;
  email?: string | null;
}

export class AuthResponse implements IAuthResponse {
  authenticationSuccess?: boolean;
  accessToken?: string | null;
  refreshToken?: string | null;
  featureCodes?: FeatureDTO[] | null;

  constructor(data?: IAuthResponse) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.authenticationSuccess =
        _data["authenticationSuccess"] !== undefined
          ? _data["authenticationSuccess"]
          : <any>null;
      this.accessToken =
        _data["accessToken"] !== undefined ? _data["accessToken"] : <any>null;
      this.refreshToken =
        _data["refreshToken"] !== undefined ? _data["refreshToken"] : <any>null;
      if (Array.isArray(_data["featureCodes"])) {
        this.featureCodes = [] as any;
        for (let item of _data["featureCodes"])
          this.featureCodes!.push(FeatureDTO.fromJS(item));
      } else {
        this.featureCodes = <any>null;
      }
    }
  }

  static fromJS(data: any): AuthResponse {
    data = typeof data === "object" ? data : {};
    let result = new AuthResponse();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["authenticationSuccess"] =
      this.authenticationSuccess !== undefined
        ? this.authenticationSuccess
        : <any>null;
    data["accessToken"] =
      this.accessToken !== undefined ? this.accessToken : <any>null;
    data["refreshToken"] =
      this.refreshToken !== undefined ? this.refreshToken : <any>null;
    if (Array.isArray(this.featureCodes)) {
      data["featureCodes"] = [];
      for (let item of this.featureCodes)
        data["featureCodes"].push(item.toJSON());
    }
    return data;
  }
}

export interface IAuthResponse {
  authenticationSuccess?: boolean;
  accessToken?: string | null;
  refreshToken?: string | null;
  featureCodes?: FeatureDTO[] | null;
}

export class FeatureDTO implements IFeatureDTO {
  featureCode?: string | null;
  route?: string | null;

  constructor(data?: IFeatureDTO) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.featureCode =
        _data["featureCode"] !== undefined ? _data["featureCode"] : <any>null;
      this.route = _data["route"] !== undefined ? _data["route"] : <any>null;
    }
  }

  static fromJS(data: any): FeatureDTO {
    data = typeof data === "object" ? data : {};
    let result = new FeatureDTO();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["featureCode"] =
      this.featureCode !== undefined ? this.featureCode : <any>null;
    data["route"] = this.route !== undefined ? this.route : <any>null;
    return data;
  }
}

export interface IFeatureDTO {
  featureCode?: string | null;
  route?: string | null;
}

export class LoginRequest implements ILoginRequest {
  login?: string | null;
  password?: string | null;

  constructor(data?: ILoginRequest) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.login = _data["login"] !== undefined ? _data["login"] : <any>null;
      this.password =
        _data["password"] !== undefined ? _data["password"] : <any>null;
    }
  }

  static fromJS(data: any): LoginRequest {
    data = typeof data === "object" ? data : {};
    let result = new LoginRequest();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["login"] = this.login !== undefined ? this.login : <any>null;
    data["password"] = this.password !== undefined ? this.password : <any>null;
    return data;
  }
}

export interface ILoginRequest {
  login?: string | null;
  password?: string | null;
}

export class RegistrationForm implements IRegistrationForm {
  userName?: string | null;
  fullName?: string | null;
  phoneNumber?: string | null;
  email?: string | null;
  password?: string | null;
  profileCode?: string | null;

  constructor(data?: IRegistrationForm) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.userName =
        _data["userName"] !== undefined ? _data["userName"] : <any>null;
      this.fullName =
        _data["fullName"] !== undefined ? _data["fullName"] : <any>null;
      this.phoneNumber =
        _data["phoneNumber"] !== undefined ? _data["phoneNumber"] : <any>null;
      this.email = _data["email"] !== undefined ? _data["email"] : <any>null;
      this.password =
        _data["password"] !== undefined ? _data["password"] : <any>null;
      this.profileCode =
        _data["profileCode"] !== undefined ? _data["profileCode"] : <any>null;
    }
  }

  static fromJS(data: any): RegistrationForm {
    data = typeof data === "object" ? data : {};
    let result = new RegistrationForm();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["userName"] = this.userName !== undefined ? this.userName : <any>null;
    data["fullName"] = this.fullName !== undefined ? this.fullName : <any>null;
    data["phoneNumber"] =
      this.phoneNumber !== undefined ? this.phoneNumber : <any>null;
    data["email"] = this.email !== undefined ? this.email : <any>null;
    data["password"] = this.password !== undefined ? this.password : <any>null;
    data["profileCode"] =
      this.profileCode !== undefined ? this.profileCode : <any>null;
    return data;
  }
}

export interface IRegistrationForm {
  userName?: string | null;
  fullName?: string | null;
  phoneNumber?: string | null;
  email?: string | null;
  password?: string | null;
  profileCode?: string | null;
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any
  ) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any
): Observable<any> {
  if (result !== null && result !== undefined) return _observableThrow(result);
  else
    return _observableThrow(
      new ApiException(message, status, response, headers, null)
    );
}

function blobToText(blob: any): Observable<string> {
  return new Observable<string>((observer: any) => {
    if (!blob) {
      observer.next("");
      observer.complete();
    } else {
      let reader = new FileReader();
      reader.onload = (event) => {
        observer.next((event.target as any).result);
        observer.complete();
      };
      reader.readAsText(blob);
    }
  });
}
